name: travelcompanionfinder
description: A web application for finding travel companions.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  intl: ^0.20.0
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/WorkSans-Regular.ttf
    - assets/fonts/WorkSans-Medium.ttf
    - assets/fonts/WorkSans-SemiBold.ttf
    - assets/fonts/WorkSans-Bold.ttf

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
