name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.part == 'backend'
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (backend)
        if: matrix.part == 'backend'
        run: npm ci
        working-directory: ./backend

      - name: Run ESLint
        if: matrix.part == 'backend'
        run: npm run lint
        working-directory: ./backend

      - name: Set up Flutter
        if: matrix.part == 'frontend'
        uses: subosito/flutter-action@v2

      - name: Disable analytics (frontend)
        if: matrix.part == 'frontend'
        run: flutter config --no-analytics

      - name: Install dependencies (frontend)
        if: matrix.part == 'frontend'
        run: flutter pub get
        working-directory: ./frontend

      - name: Run Dart format
        if: matrix.part == 'frontend'
        run: dart format --line-length 80 --set-exit-if-changed .
        working-directory: ./frontend

      - name: Run Dart analyze
        if: matrix.part == 'frontend'
        run: flutter analyze
        working-directory: ./frontend

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.part == 'backend'
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (backend)
        if: matrix.part == 'backend'
        run: npm ci
        working-directory: ./backend

      - name: Run tests (backend)
        if: matrix.part == 'backend'
        run: npm test
        working-directory: ./backend

      - name: Set up Flutter
        if: matrix.part == 'frontend'
        uses: subosito/flutter-action@v2

      - name: Disable analytics (frontend)
        if: matrix.part == 'frontend'
        run: flutter config --no-analytics

      - name: Install dependencies (frontend)
        if: matrix.part == 'frontend'
        run: flutter pub get
        working-directory: ./frontend

      - name: Run tests (frontend)
        if: matrix.part == 'frontend'
        run: flutter test
        working-directory: ./frontend

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
