name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: DockerHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=${{ secrets.NODE_ENV }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t ${{ secrets.DOCKER_USERNAME }}/backend-tcf:latest \
            ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-tcf:latest
      - name: Build and push frontend Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-tcf:latest \
            ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-tcf:latest